# Generated by Django 4.2.15 on 2024-08-26 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
